### ISSUE TITLE
libpython3.8 dependancy

### ISSUE THREAD

**Issue by FXJLK** [jacodt/rocm_dummy_packages#1]
Thank you for the dummy packages, they helped get rid of the rocm-llvm dependencies. However I still cant install rocm because of the rocm-gdb dependencies. I get this message:

The following packages have unmet dependencies:
 rocm-gdb : Depends: libpython3.8 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by FXJLK** [comment]
Nevermind, I fixed it by [installing python from the PPA](https://github.com/RadeonOpenCompute/ROCm/issues/1713#issuecomment-1107073490)

**Comment by jacodt** [comment]
Ah sorry about that. Forgot to mention in the readme that you may need to install python3.8 from the deadsnakes repo. When I have a moment I will update the documentation accordingly.

Basically just search for the deadsnakes ppa and follow the instructions to install python3.8
